services:
  mongo:
    image: "mongo"
    ports:
      - "8080:27017"
    
  backend:
    build: "./messenger-backend"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - "./messenger-backend/.env.production"
  
  frontend:
    build: 
      context: "./messenger-frontend"
      args:
        REACT_APP_API_URL: http://3.27.239.74:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
   