name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest
  
    services:
      mongo:
        image: mongo
        ports: ["27017:27017"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: waiting for mongodb to be ready
        run: |
          until nc -z localhost 27017; do
            echo "waiting for mongodb"
            sleep 2
          done
            echo "mongodb is ready"

      - name: seed mongodb
        working-directory: ./messenger-backend
        run: |
          npm install
          node seedtest.js

  tests:
    runs-on: ubuntu-latest
    needs: mongo-init

    steps:
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
         node-version: 18

      - name: install dependencies for backend
        working-directory: ./messenger-backend
        run: npm install

      - name: running test cases
        working-directory: ./messenger-backend 
        run: npm test 
     